manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/petejohanson
    - name: jewtvet
      url-base: https://github.com/jewtvet
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: feat/pointers-move-scroll
      import: app/west.yml
    - name: zmk-ruen
      remote: jewtvet
      revision: main
  self:
    path: config
